// alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// user
export const SIGN_USER_IN_SUCCESS = 'SIGN_USER_IN_SUCCESS';
export const SIGN_USER_IN_FAIL = 'SIGN_USER_IN_FAIL';

// buildings
export const ADD_BUILDING_SUCCESS = 'ADD_BUILDING_SUCCESS';
export const ADD_BUILDING_FAIL = 'ADD_BUILDING_FAIL';
export const REMOVE_BUILDING_SUCCESS = 'REMOVE_BUILDING_SUCCESS';
export const REMOVE_BUILDING_FAIL = 'REMOVE_BUILDING_FAIL';
